### ISSUE TITLE
Ground track discrepancy

### ISSUE THREAD

**Issue by johnpayne** [mihai-dinculescu/msfs-2020-gps-link#56] opened 2023-03-12 22:29 UTC
Hello,

It seems the track in MSFS 2020 disagrees with the track in GPS Link [v0.3.1] by about 10 degrees.

Example : MSFS 2020 says I'm tracking 268° and GPS Link says I'm tracking 258°.

![Microsoft Flight Simulator Screenshot 2023 03 12 - 14 31 08 15 (2)](https://user-images.githubusercontent.com/3162571/224578565-aab90636-6880-4da7-ac19-a712cdff4f64.png)

![Screenshot_20230312-143217_Avare](https://user-images.githubusercontent.com/3162571/224578577-854e5398-f58c-4ec5-b498-9bc8dcc9b70b.jpg)

I'm using an Android phone with AVARE for the external client.

**Comment by mihai-dinculescu** [comment] 2023-03-19 11:33
Thank you for reporting this.

I'll have to get a bit creative with testing.
![Screenshot_20230319_113252_Google Play Store](https://user-images.githubusercontent.com/9944681/226172542-ae8dd2d6-fc44-4ec1-92d9-68695aaad6bb.jpg)

**Comment by mihai-dinculescu** [comment] 2023-03-19 12:10
I'll try and debug it once this BlueStacks saga is over.
https://www.reddit.com/r/BlueStacks/comments/11unik2/trojan_virus/

**Comment by johnpayne** [comment] 2023-03-20 07:49
I had trouble getting my local environment to compile this code...but I made the changes I believe it needs in branch "ground_track_refactor".   See what you think.  I can retest it if you can compile it for me.

**Comment by mihai-dinculescu** [comment] 2023-03-21 22:48
The issue is with the track calculation. It correctly subtracts the westerly variation, but instead of adding the easterly one, it subtracts it.

I'll have a fix out tomorrow.

**Comment by mihai-dinculescu** [comment] 2023-03-22 19:24
Fixed in https://github.com/mihai-dinculescu/msfs-2020-gps-link/releases/tag/v0.3.2.

**Comment by johnpayne** [comment] 2023-03-25 18:39
Confirmed.  Thanks!!

**Closed as completed** 2023-04-08 11:08 UTC
